{
  lib,
  inv,
  currentHost,
  config,
  pkgs,
  ...
}:
let
  hasHost = builtins.hasAttr currentHost inv.hosts;
  host = if hasHost then inv.hosts.${currentHost} else { };
  wifi = host.wifi or null;

  wifiInterface = if wifi != null && wifi ? interface then wifi.interface else "wlan0";

  networksCfg = inv.networks or { };

  # Networks this host wants to use
  wifiNetworks = if wifi != null then wifi.networks or [ ] else [ ];

  wifiMode = if wifi == null then null else (wifi.mode or null);

  isRoaming = hasHost && wifi != null && wifiMode == "roaming";
  roamingHasNetworks = isRoaming && (wifiNetworks != [ ]);

  # Networks with secrets (used by static-wifi + wireless.conf)
  networksWithPassword = lib.filterAttrs (_: net: net ? passwordSecret) networksCfg;

  wifiNetworksWithPassword = lib.filterAttrs (
    netName: _: lib.elem netName wifiNetworks
  ) networksWithPassword;

  mkWirelessNetworks =
    wifiCfg:
    let
      netNames = wifiCfg.networks or [ ];
    in
    lib.foldl' (
      acc: netName:
      let
        net = networksCfg.${netName};
        ssid = net.ssid;
      in
      acc
      // {
        "${ssid}" = {
          pskRaw = "ext:psk_${netName}";
        };
      }
    ) { } netNames;

  # Namespace UUID for deterministic NetworkManager connection UUIDs.
  # DO NOT change: would regenerate UUIDs and create duplicate NM profiles.
  nmNamespace = "e6b4b7a5-9df1-4c1d-9d3f-2c8d0a9f0c2a";

  # Package the external script (keeps Nix strings small; LSP stays sane)
  nmProfilesScript = pkgs.writeShellApplication {
    name = "snowman-networkmanager-profiles";
    runtimeInputs = with pkgs; [
      coreutils
      util-linux
      systemd
    ];
    text = builtins.readFile ../scripts/snowman-networkmanager-profiles.sh;
  };

  # TSV lines: netName<TAB>ssid<TAB>pskFileOrEmpty
  nmNetList = lib.concatStringsSep "\n" (
    map (
      netName:
      let
        net = networksCfg.${netName};
        ssid = net.ssid;

        secretName = "wifi-${netName}-password";
        secretPath = if net ? passwordSecret then config.sops.secrets.${secretName}.path else "";
      in
      "${netName}	${ssid}	${toString secretPath}"
    ) wifiNetworks
  );

in
{
  config = lib.mkMerge [
    # -------------------------------------------------------------------------
    # Static Wi-Fi mode (wpa_supplicant + ext:psk)
    # -------------------------------------------------------------------------
    (lib.mkIf (hasHost && wifi != null && wifi.mode == "static-wifi") {
      networking.useDHCP = wifi.useDHCP or true;

      networking.networkmanager.enable = false;
      networking.wireless.enable = true;
      networking.wireless.interfaces = [ wifiInterface ];

      networking.wireless.networks = mkWirelessNetworks wifi;

      networking.firewall = {
        enable = lib.mkDefault true;
        trustedInterfaces = lib.mkDefault [ wifiInterface ];
        checkReversePath = lib.mkDefault "loose";
        allowPing = lib.mkDefault true;
      };
    })

    # -------------------------------------------------------------------------
    # Roaming Wi-Fi via NetworkManager (+ optional provisioning)
    # -------------------------------------------------------------------------
    (lib.mkIf isRoaming (
      lib.mkMerge [
        {
          networking.useDHCP = lib.mkForce false;
          networking.networkmanager.enable = true;
          networking.wireless.enable = false;
        }

        (lib.mkIf roamingHasNetworks {
          system.activationScripts."snowman-networkmanager-profiles" = ''
            set -euo pipefail

            listFile="$(mktemp)"
            trap 'rm -f "$listFile"' EXIT

            cat > "$listFile" <<'EOF'
            ${nmNetList}
            EOF

            ${nmProfilesScript}/bin/snowman-networkmanager-profiles \
              ${lib.escapeShellArg nmNamespace} \
              /etc/NetworkManager/system-connections \
              "$listFile"
          '';
        })
      ]
    ))

    # -------------------------------------------------------------------------
    # Generate /run/secrets/wireless.conf for ext:psk_<net>
    # (used by static-wifi)
    # -------------------------------------------------------------------------
    (lib.mkIf (hasHost && wifi != null && wifiNetworksWithPassword != { }) {
      networking.wireless.secretsFile = "/run/secrets/wireless.conf";

      system.activationScripts."snowman-wireless-secrets" = ''
        set -u
        set -o pipefail

        outfile="/run/secrets/wireless.conf"
        mkdir -p /run/secrets
        : > "$outfile"

        echo "# Generated by Snowman" >> "$outfile"

        ${lib.concatStringsSep "\n" (
          lib.mapAttrsToList (
            netName: net:
            let
              secretName = "wifi-${netName}-password";
              secretPath = config.sops.secrets.${secretName}.path;
            in
            ''
              if [ -r ${lib.escapeShellArg secretPath} ]; then
                echo "psk_${netName}=$(cat ${lib.escapeShellArg secretPath})" >> "$outfile"
              else
                echo "[snowman] WARNING: Secret file ${secretPath} for network ${netName} is missing or unreadable." >&2
              fi
            ''
          ) wifiNetworksWithPassword
        )}

        chown root:root "$outfile"
        chmod 0400 "$outfile"
      '';
    })

    # -------------------------------------------------------------------------
    # Assertions
    # -------------------------------------------------------------------------
    {
      assertions = [
        {
          assertion =
            !(hasHost && wifi != null && wifi.mode == "static-wifi") || (wifi.networks or [ ]) != [ ];
          message = ''
            Host ${currentHost}: wifi.mode = "static-wifi" but wifi.networks is empty.
          '';
        }
        {
          assertion =
            !(hasHost && wifi != null)
            || lib.all (netName: builtins.hasAttr netName networksCfg) (wifi.networks or [ ]);
          message = "Host ${currentHost}: wifi.networks references undefined entries in inventory.networks.";
        }
      ];
    }
  ];
}
