{ lib, inv, currentHost, config, ... }:
let
  hasHost = builtins.hasAttr currentHost inv.hosts;
  host = if hasHost then inv.hosts.${currentHost} else { };
  wifi = host.wifi or null;

  wifiInterface =
    if wifi != null && wifi ? interface then wifi.interface else "wlan0";

  networksCfg = inv.networks or { };

  # Networks that declare a passwordSecret
  networksWithPassword =
    lib.filterAttrs (_: net: net ? passwordSecret) networksCfg;

  mkWirelessNetworks = wifiCfg:
    let netNames = wifiCfg.networks or [ ];
    in lib.foldl' (acc: netName:
      let
        net = networksCfg.${netName};
        ssid = net.ssid;
      in acc // {
        "${ssid}" = {
          # wpa_supplicant will look up this symbol in wireless.conf
          pskRaw = "ext:psk_${netName}";
        };
      }) { } netNames;

in {
  config = lib.mkMerge [
    # --- Static Wi-Fi mode (wpa_supplicant + ext password) --------------------
    (lib.mkIf (hasHost && wifi != null && wifi.mode == "static-wifi") {
      networking.useDHCP = wifi.useDHCP or true;

      networking.networkmanager.enable = false;
      networking.wireless.enable = true;
      networking.wireless.interfaces = [ wifi.interface or "wlan0" ];

      networking.wireless.networks = mkWirelessNetworks wifi;
    })

    # --- Roaming mode via NetworkManager --------------------------------------
    (lib.mkIf (hasHost && wifi != null && wifi.mode == "roaming") {
      networking.useDHCP = wifi.useDHCP or true;
      networking.networkmanager.enable = true;
      networking.wireless.enable = false;
    })

    # --- Generate /run/secrets/wireless.conf for ext:psk_<net> ---------------
    (lib.mkIf (hasHost && wifi != null && networksWithPassword != { }) {
      networking.wireless.secretsFile = "/run/secrets/wireless.conf";

      system.activationScripts."snowman-wireless-secrets" = ''
        set -euo pipefail

        outfile="/run/secrets/wireless.conf"
        mkdir -p /run/secrets
        : > "$outfile"

        echo "# Generated by Snowman" >> "$outfile"

        ${lib.concatStringsSep "\n" (lib.mapAttrsToList (netName: net:
          let
            secretName = "wifi-${netName}-password";
            secretPath = config.sops.secrets.${secretName}.path;
          in ''
            # Secret for Wi-Fi network ${netName}
            if [ -r ${lib.escapeShellArg secretPath} ]; then
              echo "psk_${netName}=$(cat ${
                lib.escapeShellArg secretPath
              })" >> "$outfile"
            else
              echo "[snowman] WARNING: Secret file ${secretPath} for network ${netName} is missing or unreadable." >&2
            fi
          '') networksWithPassword)}

        chown root:root "$outfile"
        chmod 0400 "$outfile"

        echo "[snowman] Created /run/secrets/wireless.conf"
      '';
    })

    # --- Wi-Fi aware firewall defaults ---------------------------------------
    (lib.mkIf (hasHost && wifi != null && wifi.mode == "static-wifi") {
      networking.firewall = {
        enable = lib.mkDefault true;
        trustedInterfaces = lib.mkDefault [ wifiInterface ];
        checkReversePath = lib.mkDefault "loose";
        allowPing = lib.mkDefault true;
      };
    })

    {
      assertions = [
        {
          assertion = !(hasHost && wifi != null && wifi.mode == "static-wifi")
            || (wifi.networks or [ ]) != [ ];
          message = ''
            Host ${currentHost}: wifi.mode = "static-wifi" but wifi.networks is empty.
          '';
        }
        {
          assertion = !(hasHost && wifi != null && wifi.mode == "static-wifi")
            || lib.all (netName: builtins.hasAttr netName networksCfg)
            (wifi.networks or [ ]);
          message =
            "Host ${currentHost}: wifi.networks references undefined entries in inventory.networks.";
        }
      ];
    }
  ];
}
