# Individual keys
.keys:
  snowmankey_usb: &snowmankey_usb age1...<your age public key from the SNOWMANKEY USB drive>
  myuser_myhost: &myuser_myhost age1...<public key of a user>

  myhost: &myhost age1...<age key derrived from host's public ssh key>

# Groups
.user_keys: &user_keys
  - *snowmankey_usb
  - *myuser_myhost

.host_keys: &host_keys
  - *myhost

.all_keys: &all_keys
  - *snowmankey_usb
  - *myuser_myhost
  - *myhost

creation_rules:
  # networks/secrets.yml
  - path_regex: ^networks/secrets\.(yml|yaml)$
    shamir_threshold: 1
    key_groups:
      - age: *all_keys

  # users/secrets/*_secrets.yml
  - path_regex: ^users/secrets/.+_secrets\.(yml|yaml)$
    shamir_threshold: 1
    key_groups:
      - age: *all_keys

  # hosts/secrets/*_secrets.yml
  - path_regex: ^hosts/secrets/.+_secrets\.(yml|yaml)$
    key_groups:
      - age: *host_keys

  - path_regex: ^secrets\.(yml|yaml)$
    shamir_threshold: 1
    key_groups:
      - age: *all_keys
